class HdlTypelist {

    async found(id) {
        return this.list[id] != undefined;
    }

    async typeOfDevice(id) {
        if (this.list[id] == undefined) return null;

        return this.list[id].type;
    }

    async numberOfChannels(id) {
        if (this.list[id] == undefined) return null;

        return this.list[id].channels;
    }

    async mainCapability(id) {
        if (this.list[id] == undefined) return null;

        return this.list[id].main_capability;
    }

    async excludeCapabilities(id) {
        if (this.list[id] == undefined) return null;

        return this.list[id].exclude;
    }


    get list() {
        return {
            "16": { type: "dimmer", channels: 48 },
            "17": { type: "dimmer", channels:6 },
            "18": { type: "dimmer", channels: 48 },
            "32": { type: "dimmer", channels: 48 },
            "35": { type: "dimmer", channels: 4 },
            "36": { type: "dimmer", channels: 6 },
            "37": { type: "dimmer", channels: 2 },
            "40": { type: "dimmer", channels: 48 },
            "41": { type: "dimmer", channels: 48 },
            "42": { type: "dimmer", channels: 64 },
            "43": { type: "dimmer", channels: 64 },
            "48": { type: "panel" },
            "49": { type: "panel" },
            "124": { type: "tempsensor", channels: 2 },
            "134": { type: "tempsensor", channels: 4 },
            "149": { type: "panel" },
            "154": { type: "panel" },
            "155": { type: "panel" },
            "156": { type: "panel" },
            "157": { type: "panel" },
            "158": { type: "panel" },
            "159": { type: "panel" },
            "160": { type: "panel" },
            "162": { type: "panel" },
            "165": { type: "panel" },
            "167": { type: "panel" },
            "168": { type: "panel" },
            "170": { type: "panel" },
            "172": { type: "panel" },
            "175": { type: "panel" },
            "176": { type: "panel" },
            "180": { type: "panel" },
            "186": { type: "panel" },
            "188": { type: "panel" },
            "196": { type: "panel" },
            "198": { type: "panel" },
            "207": { type: "floorheater", channels: 6 },
            "208": { type: "floorheater", channels: 6 },
            "209": { type: "floorheater", channels: 6 },
            "210": { type: "floorheater", channels: 6 },
            "211": { type: "floorheater", channels: 6 },
            "212": { type: "floorheater", channels: 6 },
            "305": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "307": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "308": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "309": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "310": { type: "multisensor", main_capability: "measure_humidity", exclude: ["alarm_motion"]},
            "312": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "314": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "315": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "316": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "318": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "321": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "322": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "323": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "327": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "328": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "329": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "330": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "334": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "336": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "337": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "328": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "340": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "341": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "363": { type: "relay", channels: 6 },
            "372": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "423": { type: "relay", channels: 4 },
            "425": { type: "relay", channels: 6 },
            "426": { type: "relay", channels: 6 },
            "427": { type: "relay", channels: 8 },
            "428": { type: "relay", channels: 8 },
            "429": { type: "relay", channels: 12 },
            "430": { type: "relay", channels: 12 },
            "431": { type: "relay", channels: 12 },
            "432": { type: "relay", channels: 24 },
            "433": { type: "relay", channels: 4 },
            "434": { type: "relay", channels: 4 },
            "435": { type: "relay", channels: 4 },
            "436": { type: "relay", channels: 8 },
            "437": { type: "relay", channels: 4 },
            "438": { type: "relay", channels: 4 },
            "439": { type: "relay", channels: 8 },
            "440": { type: "relay", channels: 12 },
            "441": { type: "relay", channels: 4 },
            "442": { type: "relay", channels: 8 },
            "443": { type: "relay", channels: 12 },
            "444": { type: "relay", channels: 4 },
            "445": { type: "relay", channels: 8 },
            "446": { type: "relay", channels: 12 },
            "447": { type: "relay", channels: 4 },
            "448": { type: "relay", channels: 8 },
            "449": { type: "relay", channels: 12 },
            "450": { type: "relay", channels: 16 },
            "451": { type: "relay", channels: 16 },
            "454": { type: "relay", channels: 3 },
            "456": { type: "relay", channels: 8 },
            "457": { type: "relay", channels: 3 },
            "458": { type: "relay", channels: 4 },
            "459": { type: "relay", channels: 4 },
            "460": { type: "relay", channels: 8 },
            "461": { type: "relay", channels: 12 },
            "462": { type: "relay", channels: 4 },
            "463": { type: "relay", channels: 8 },
            "464": { type: "relay", channels: 12 },
            "465": { type: "relay", channels: 16 },
            "466": { type: "relay", channels: 16 },
            "467": { type: "relay", channels: 3 },
            "468": { type: "relay", channels: 6 },
            "469": { type: "relay", channels: 4 },
            "470": { type: "relay", channels: 6 },
            "600": { type: "dimmer", channels: 6 },
            "601": { type: "dimmer", channels: 4 },
            "602": { type: "dimmer", channels: 2 },
            "606": { type: "dimmer", channels: 2 },
            "607": { type: "dimmer", channels: 4 },
            "608": { type: "dimmer", channels: 6 },
            "609": { type: "dimmer", channels: 1 },
            "610": { type: "dimmer", channels: 6 },
            "611": { type: "dimmer", channels: 4 },
            "612": { type: "dimmer", channels: 2 },
            "613": { type: "dimmer", channels: 6 },
            "614": { type: "dimmer", channels: 2 },
            "615": { type: "dimmer", channels: 4 },
            "616": { type: "dimmer", channels: 4 },
            "617": { type: "dimmer", channels: 6 },
            "618": { type: "dimmer", channels: 1 },
            "619": { type: "dimmer", channels: 2 },
            "620": { type: "dimmer", channels: 4 },
            "621": { type: "dimmer", channels: 6 },
            "622": { type: "dimmer", channels: 6 },
            "623": { type: "dimmer", channels: 4 },
            "630": { type: "dimmer", channels: 4 },
            "631": { type: "dimmer", channels: 2 },
            "632": { type: "dimmer", channels: 4 },
            "633": { type: "dimmer", channels: 6 },
            "634": { type: "dimmer", channels: 2 },
            "635": { type: "dimmer", channels: 4 },
            "636": { type: "dimmer", channels: 6 },
            "637": { type: "dimmer", channels: 2 },
            "638": { type: "dimmer", channels: 6 },
            "639": { type: "dimmer", channels: 2 },
            "640": { type: "dimmer", channels: 4 },
            "641": { type: "dimmer", channels: 6 },
            "642": { type: "dimmer", channels: 2 },
            "643": { type: "dimmer", channels: 4 },
            "644": { type: "dimmer", channels: 6 },
            "645": { type: "dimmer", channels: 4 },
            "646": { type: "dimmer", channels: 6 },
            "647": { type: "dimmer", channels: 6 },
            "648": { type: "dimmer", channels: 6 },
            "649": { type: "dimmer", channels: 6 },
            "651": { type: "dimmer", channels: 2 },
            "652": { type: "dimmer", channels: 4 },
            "653": { type: "dimmer", channels: 6 },
            "654": { type: "dimmer", channels: 6 },
            "655": { type: "dimmer", channels: 6 },
            "656": { type: "dimmer", channels: 6 },
            "657": { type: "dimmer", channels: 2 },
            "658": { type: "dimmer", channels: 6 },
            "659": { type: "dimmer", channels: 2 },
            "660": { type: "dimmer", channels: 4 },
            "661": { type: "dimmer", channels: 6 },
            "662": { type: "dimmer", channels: 6 },
            "663": { type: "dimmer", channels: 2 },
            "664": { type: "dimmer", channels: 4 },
            "665": { type: "dimmer", channels: 6 },
            "666": { type: "dimmer", channels: 6 },
            "667": { type: "dimmer", channels: 4 },
            "668": { type: "dimmer", channels: 2 },
            "700": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "701": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "702": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "703": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "704": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "705": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "706": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "707": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "713": { type: "curtain", channels: 2, hasDuration: true, hasLevelMonitor: false },
            "719": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },      
            "800": { type: "dimmer", channels: 8 },
            "850": { type: "dimmer", channels: 96 },
            "851": { type: "dimmer", channels: 96 },
            "852": { type: "dimmer", channels: 96 },
            "853": { type: "dimmer", channels: 48 },
            "854": { type: "dimmer", channels: 48 },
            "2058": { type: "panel" },
            "4300": { type: "dimmer", channels: 64 },
            "4301": { type: "dimmer", channels: 64 },
            "4302": { type: "dimmer", channels: 64 },
            "5001": { type: "panel" },
            "5002": { type: "panel" },
            "5003": { type: "panel" },
            "5004": { type: "panel" },
            "5006": { type: "panel" },
            "5007": { type: "panel" },
            "9001": { type: "panel" },
            "9111": { type: "panel" },
        };
    }
}

module.exports = HdlTypelist;