class HdlTypelist {

    async found(id) {
        return this.list[id] != undefined;
    }

    async typeOfDevice(id) {
        if (this.list[id] == undefined) return null;
        if (this.list[id].type == undefined) return null;

        return this.list[id].type;
    }

    async numberOfChannels(id) {
        if (this.list[id] == undefined) return null;
        if (this.list[id].channels == undefined) return 0;

        return this.list[id].channels;
    }

    async numberOfZones(id) {
        if (this.list[id] == undefined) return null;
        if (this.list[id].zones == undefined) return 0;

        return this.list[id].zones;
    }

    async mainCapability(id) {
        if (this.list[id] == undefined) return null;
        if (this.list[id].main_capability == undefined) return null;

        return this.list[id].main_capability;
    }

    async excludeCapabilities(id) {
        if (this.list[id] == undefined) return null;
        if (this.list[id].exclude == undefined) return [];

        return this.list[id].exclude;
    }


    get list() {
        return {
            "16": { type: "dimmer", channels: 48, zones: 0 },
            "17": { type: "dimmer", channels:6, zones: 0 },
            "18": { type: "dimmer", channels: 48, zones: 0 },
            "32": { type: "dimmer", channels: 48, zones: 0 },
            "35": { type: "dimmer", channels: 4, zones: 0 },
            "36": { type: "dimmer", channels: 6, zones: 0 },
            "37": { type: "dimmer", channels: 2, zones: 0 },
            "40": { type: "dimmer", channels: 48, zones: 0 },
            "41": { type: "dimmer", channels: 48, zones: 0 },
            "42": { type: "dimmer", channels: 64, zones: 0 },
            "43": { type: "dimmer", channels: 64, zones: 0 },
            "48": { type: "panel" },
            "49": { type: "panel" },
            "84": { type: "panel" },
            "124": { type: "tempsensor", channels: 2 },
            "134": { type: "tempsensor", channels: 4 },
            "149": { type: "panel" },
            "150": { type: "relay", channels: 12 },
            "151": { type: "relay", channels: 24 },
            "152": { type: "relay", channels: 6 },
            "153": { type: "relay", channels: 4 },
            "154": { type: "panel" },
            "155": { type: "panel" },
            "156": { type: "panel" },
            "157": { type: "panel" },
            "158": { type: "panel" },
            "159": { type: "panel" },
            "160": { type: "panel" },
            "162": { type: "panel" },
            "165": { type: "panel" },
            "167": { type: "panel" },
            "168": { type: "panel" },
            "170": { type: "panel" },
            "172": { type: "panel" },
            "175": { type: "panel" },
            "176": { type: "panel" },
            "180": { type: "panel" },
            "186": { type: "panel" },
            "188": { type: "panel" },
            "196": { type: "panel" },
            "198": { type: "panel" },
            "207": { type: "floorheater", channels: 6 },
            "208": { type: "floorheater", channels: 6 },
            "209": { type: "floorheater", channels: 6 },
            "210": { type: "floorheater", channels: 6 },
            "211": { type: "floorheater", channels: 6 },
            "212": { type: "floorheater", channels: 6 },
            "305": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "307": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "308": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "309": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "310": { type: "multisensor", main_capability: "measure_humidity", exclude: ["alarm_motion"]},
            "312": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "314": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "315": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "316": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "318": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "321": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "322": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "323": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity"]},
            "327": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "328": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "329": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "330": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "334": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "336": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "337": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "328": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "340": { type: "multisensor", main_capability: "alarm_motion", exclude: []},
            "341": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "363": { type: "relay", channels: 6 },
            "365": { type: "tempsensor", channels: 4 },
            "371": { type: "tempsensor", channels: 4 },
            "372": { type: "multisensor", main_capability: "alarm_motion", exclude: ["measure_humidity", "measure_temperature"]},
            "374": { type: "tempsensor", channels: 4 },
            "378": { type: "tempsensor", channels: 4 },
            "381": { type: "tempsensor", channels: 4 },
            "382": { type: "tempsensor", channels: 4 },
            "384": { type: "tempsensor", channels: 6 },
            "385": { type: "tempsensor", channels: 4 },
            "387": { type: "tempsensor", channels: 4 },
            "423": { type: "relay", channels: 4 },
            "425": { type: "relay", channels: 6 },
            "426": { type: "relay", channels: 6 },
            "427": { type: "relay", channels: 8 },
            "428": { type: "relay", channels: 8 },
            "429": { type: "relay", channels: 12 },
            "430": { type: "relay", channels: 12 },
            "431": { type: "relay", channels: 12 },
            "432": { type: "relay", channels: 24 },
            "433": { type: "relay", channels: 4 },
            "434": { type: "relay", channels: 4 },
            "435": { type: "relay", channels: 4 },
            "436": { type: "relay", channels: 8 },
            "437": { type: "relay", channels: 4 },
            "438": { type: "relay", channels: 4 },
            "439": { type: "relay", channels: 8 },
            "440": { type: "relay", channels: 12 },
            "441": { type: "relay", channels: 4 },
            "442": { type: "relay", channels: 8 },
            "443": { type: "relay", channels: 12 },
            "444": { type: "relay", channels: 4 },
            "445": { type: "relay", channels: 8 },
            "446": { type: "relay", channels: 12 },
            "447": { type: "relay", channels: 4 },
            "448": { type: "relay", channels: 8 },
            "449": { type: "relay", channels: 12 },
            "450": { type: "relay", channels: 16 },
            "451": { type: "relay", channels: 16 },
            "454": { type: "relay", channels: 3 },
            "456": { type: "relay", channels: 8 },
            "457": { type: "relay", channels: 3 },
            "458": { type: "relay", channels: 4 },
            "459": { type: "relay", channels: 4 },
            "460": { type: "relay", channels: 8 },
            "461": { type: "relay", channels: 12 },
            "462": { type: "relay", channels: 4 },
            "463": { type: "relay", channels: 8 },
            "464": { type: "relay", channels: 12 },
            "465": { type: "relay", channels: 16 },
            "466": { type: "relay", channels: 16 },
            "467": { type: "relay", channels: 3 },
            "468": { type: "relay", channels: 6 },
            "469": { type: "relay", channels: 4 },
            "470": { type: "relay", channels: 6 },
            "471": { type: "relay", channels: 12 },
            "472": { type: "relay", channels: 12 },
            "473": { type: "relay", channels: 4 },
            "474": { type: "relay", channels: 8 },
            "475": { type: "relay", channels: 12 },
            "476": { type: "relay", channels: 4 },
            "477": { type: "relay", channels: 8 },
            "478": { type: "relay", channels: 4 },
            "479": { type: "relay", channels: 8 },
            "480": { type: "relay", channels: 12 },
            "481": { type: "relay", channels: 4 },
            "482": { type: "relay", channels: 8 },
            "483": { type: "relay", channels: 12 },
            "485": { type: "relay", channels: 12 },
            "486": { type: "relay", channels: 8 },
            "487": { type: "relay", channels: 4 },
            "488": { type: "relay", channels: 8 },
            "489": { type: "relay", channels: 12 },
            "495": { type: "relay", channels: 8 },
            "498": { type: "relay", channels: 8 },
            "498": { type: "relay", channels: 8 },
            "498": { type: "relay", channels: 8 },
            "498": { type: "relay", channels: 8 },
            "501": { type: "relay", channels: 3 },
            "502": { type: "relay", channels: 4 },
            "503": { type: "relay", channels: 8 },
            "504": { type: "relay", channels: 12 },
            "505": { type: "relay", channels: 4 },
            "506": { type: "relay", channels: 8 },
            "507": { type: "relay", channels: 6 },
            "512": { type: "relay", channels: 12 },
            "513": { type: "relay", channels: 4 },
            "514": { type: "relay", channels: 8 },
            "515": { type: "relay", channels: 12 },
            "600": { type: "dimmer", channels: 6, zones: 0 },
            "601": { type: "dimmer", channels: 4, zones: 0 },
            "602": { type: "dimmer", channels: 2, zones: 0 },
            "606": { type: "dimmer", channels: 2, zones: 0 },
            "607": { type: "dimmer", channels: 4, zones: 0 },
            "608": { type: "dimmer", channels: 6, zones: 0 },
            "609": { type: "dimmer", channels: 1, zones: 0 },
            "610": { type: "dimmer", channels: 6, zones: 0 },
            "611": { type: "dimmer", channels: 4, zones: 0 },
            "612": { type: "dimmer", channels: 2, zones: 0 },
            "613": { type: "dimmer", channels: 6, zones: 0 },
            "614": { type: "dimmer", channels: 2, zones: 0 },
            "615": { type: "dimmer", channels: 4, zones: 0 },
            "616": { type: "dimmer", channels: 4, zones: 0 },
            "617": { type: "dimmer", channels: 6, zones: 0 },
            "618": { type: "dimmer", channels: 1, zones: 0 },
            "619": { type: "dimmer", channels: 2, zones: 0 },
            "620": { type: "dimmer", channels: 4, zones: 0 },
            "621": { type: "dimmer", channels: 6, zones: 0 },
            "622": { type: "dimmer", channels: 6, zones: 0 },
            "623": { type: "dimmer", channels: 4, zones: 0 },
            "630": { type: "dimmer", channels: 4, zones: 0 },
            "631": { type: "dimmer", channels: 2, zones: 0 },
            "632": { type: "dimmer", channels: 4, zones: 0 },
            "633": { type: "dimmer", channels: 6, zones: 0 },
            "634": { type: "dimmer", channels: 2, zones: 0 },
            "635": { type: "dimmer", channels: 4, zones: 0 },
            "636": { type: "dimmer", channels: 6, zones: 0 },
            "637": { type: "dimmer", channels: 2, zones: 0 },
            "638": { type: "dimmer", channels: 6, zones: 0 },
            "639": { type: "dimmer", channels: 2, zones: 0 },
            "640": { type: "dimmer", channels: 4, zones: 0 },
            "641": { type: "dimmer", channels: 6, zones: 0 },
            "642": { type: "dimmer", channels: 2, zones: 0 },
            "643": { type: "dimmer", channels: 4, zones: 0 },
            "644": { type: "dimmer", channels: 6, zones: 0 },
            "645": { type: "dimmer", channels: 4, zones: 0 },
            "646": { type: "dimmer", channels: 6, zones: 0 },
            "647": { type: "dimmer", channels: 6, zones: 0 },
            "648": { type: "dimmer", channels: 6, zones: 0 },
            "649": { type: "dimmer", channels: 6, zones: 0 },
            "651": { type: "dimmer", channels: 2, zones: 0 },
            "652": { type: "dimmer", channels: 4, zones: 0 },
            "653": { type: "dimmer", channels: 6, zones: 0 },
            "654": { type: "dimmer", channels: 6, zones: 0 },
            "655": { type: "dimmer", channels: 6, zones: 0 },
            "656": { type: "dimmer", channels: 6, zones: 0 },
            "657": { type: "dimmer", channels: 2, zones: 0 },
            "658": { type: "dimmer", channels: 6, zones: 0 },
            "659": { type: "dimmer", channels: 2, zones: 0 },
            "660": { type: "dimmer", channels: 4, zones: 0 },
            "661": { type: "dimmer", channels: 6, zones: 0 },
            "662": { type: "dimmer", channels: 6, zones: 0 },
            "663": { type: "dimmer", channels: 2, zones: 0 },
            "664": { type: "dimmer", channels: 4, zones: 0 },
            "665": { type: "dimmer", channels: 6, zones: 0 },
            "666": { type: "dimmer", channels: 6, zones: 0 },
            "667": { type: "dimmer", channels: 4, zones: 0 },
            "668": { type: "dimmer", channels: 2, zones: 0 },
            "700": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "701": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "702": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "703": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "704": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "705": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "706": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "707": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },
            "713": { type: "curtain", channels: 2, hasDuration: true, hasLevelMonitor: false },
            "719": { type: "curtain", channels: 2, hasDuration: undefined, hasLevelMonitor: undefined },      
            "800": { type: "dimmer", channels: 8, zones: 0 },
            "850": { type: "dimmer", channels: 96, zones: 0 },
            "851": { type: "dimmer", channels: 96, zones: 0 },
            "852": { type: "dimmer", channels: 96, zones: 0 },
            "853": { type: "dimmer", channels: 48, zones: 0 },
            "854": { type: "dimmer", channels: 48, zones: 0 },
            "2055": { type: "panel" },
            "2056": { type: "panel" },
            "2057": { type: "panel" },
            "2058": { type: "panel" },
            "2062": { type: "panel" },
            "2063": { type: "panel" },
            "2064": { type: "panel" },
            "2065": { type: "panel" },
            "2066": { type: "panel" },
            "2067": { type: "panel" },
            "2068": { type: "panel" },
            "2069": { type: "panel" },
            "2070": { type: "panel" },
            "2071": { type: "panel" },
            "2072": { type: "panel" },
            "2085": { type: "panel" },
            "2086": { type: "panel" },
            "2087": { type: "panel" },
            "2088": { type: "panel" },
            "2089": { type: "panel" },
            "2090": { type: "panel" },
            "2091": { type: "panel" },
            "2092": { type: "panel" },
            "2093": { type: "panel" },
            "2094": { type: "panel" },
            "2095": { type: "panel" },
            "2096": { type: "panel" },
            "2097": { type: "panel" },
            "2098": { type: "panel" },
            "2099": { type: "panel" },
            "2100": { type: "panel" },
            "2101": { type: "panel" },
            "2102": { type: "panel" },
            "2103": { type: "panel" },
            "2104": { type: "panel" },
            "2105": { type: "panel" },
            "2106": { type: "panel" },
            "2107": { type: "panel" },
            "2124": { type: "panel" },
            "2125": { type: "panel" },
            "2126": { type: "panel" },
            "2127": { type: "panel" },
            "2128": { type: "panel" },
            "2129": { type: "panel" },
            "2130": { type: "panel" },
            "2131": { type: "panel" },
            "2132": { type: "panel" },
            "2133": { type: "panel" },
            "2162": { type: "panel" },
            "2263": { type: "panel" },
            "2264": { type: "panel" },
            "2267": { type: "panel" },
            "2268": { type: "panel" },
            "4300": { type: "dimmer", channels: 64, zones: 16 },
            "4301": { type: "dimmer", channels: 64, zones: 16 },
            "4302": { type: "dimmer", channels: 64, zones: 16 },
            "4303": { type: "dimmer", channels: 64, zones: 16 },
            "4304": { type: "dimmer", channels: 64, zones: 16 },
            "4305": { type: "dimmer", channels: 64, zones: 16 },
            "4306": { type: "dimmer", channels: 64, zones: 16 },
            "4307": { type: "dimmer", channels: 64, zones: 16 },
            "5001": { type: "panel" },
            "5002": { type: "panel" },
            "5003": { type: "panel" },
            "5004": { type: "panel" },
            "5006": { type: "panel" },
            "5007": { type: "panel" },
            "9001": { type: "panel" },
            "9111": { type: "panel" },
        };
    }
}

module.exports = HdlTypelist;